version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: news-api
    env_file: .env
    volumes:
      - .:/home/app
    container_name: news-back
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=$NODE_ENV

  mongo:
      container_name: mongo-container
      image: mongo:latest
      restart: always
      ports: 
          - 27017:27017
      environment:
          MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
          MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
          MONGO_INITDB_ROOT_DATABASE: $DB_NAME
      
      volumes:
          - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
          - ~/mongo/data:/data/db
